# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - pod install --project-directory=PhotoAlbum
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace PhotoAlbum/PhotoAlbum.xcworkspace -scheme PhotoAlbum
