# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'PhotoAlbum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoAlbum
  pod "VK-ios-sdk"

  target 'PhotoAlbumTests' do
    inherit! :search_paths
    pod "VK-ios-sdk" 
  end

end
